#!/usr/bin/env bash
set -euo pipefail

RUN_ID="${1:-}"

if [[ -z "${GITHUB_TOKEN:-}" ]]; then
  echo "GITHUB_TOKEN is required."
  exit 1
fi

if [[ -z "${RUN_ID}" ]]; then
  RUN_ID="$(gh run list --workflow CI --branch main --json databaseId,conclusion -L 20 | node -e "const fs=require('fs');const d=JSON.parse(fs.readFileSync(0,'utf8'));const r=d.find(x=>x.conclusion==='failure');if(r)process.stdout.write(String(r.databaseId));")"
fi

if [[ -z "${RUN_ID}" ]]; then
  echo "No failed CI run found."
  exit 0
fi

RUN_JSON="$(gh run view "${RUN_ID}" --json databaseId,headSha,headBranch,url,conclusion,workflowName)"
CONCLUSION="$(node -e "const d=JSON.parse(process.argv[1]);process.stdout.write(d.conclusion||'')" "${RUN_JSON}")"
HEAD_SHA="$(node -e "const d=JSON.parse(process.argv[1]);process.stdout.write(d.headSha||'')" "${RUN_JSON}")"
HEAD_BRANCH="$(node -e "const d=JSON.parse(process.argv[1]);process.stdout.write(d.headBranch||'')" "${RUN_JSON}")"
RUN_URL="$(node -e "const d=JSON.parse(process.argv[1]);process.stdout.write(d.url||'')" "${RUN_JSON}")"
FAILED_JOB_SUMMARY="$(
  gh run view "${RUN_ID}" --json jobs,url \
    | node -e "const fs=require('fs');const data=JSON.parse(fs.readFileSync(0,'utf8'));const jobs=Array.isArray(data.jobs)?data.jobs:[];const failed=jobs.filter(j=>j.conclusion==='failure');if(!failed.length){process.stdout.write('- no failed jobs parsed (check run logs manually).');process.exit(0);}const lines=failed.slice(0,5).map((j)=>{const failedStep=(Array.isArray(j.steps)?j.steps:[]).find(s=>s.conclusion==='failure');const stepPart=failedStep?.name?` (step: ${failedStep.name})`:'';const urlPart=j.url?` - ${j.url}`:'';return `- ${j.name}${stepPart}${urlPart}`;});process.stdout.write(lines.join('\n'));" || true
)"
if [[ -z "${FAILED_JOB_SUMMARY}" ]]; then
  FAILED_JOB_SUMMARY="- no failed jobs parsed (check run logs manually)."
fi

if [[ "${CONCLUSION}" != "failure" ]]; then
  echo "Run ${RUN_ID} is not failing now."
  exit 0
fi

if [[ "${HEAD_BRANCH}" != "main" ]]; then
  echo "Skip non-main branch failure: ${HEAD_BRANCH}"
  exit 0
fi

git fetch origin main

git checkout -B main "${HEAD_SHA}"

set +e
npm install >/tmp/ci-watchdog-npm-install.log 2>&1
INSTALL_CODE="$?"
set -e

if [[ "${INSTALL_CODE}" -ne 0 ]]; then
  echo "npm install failed, cannot auto-fix deterministically."
else
  if ! git diff --quiet -- package-lock.json; then
    TS="$(date -u +%Y%m%d%H%M%S)"
    BRANCH="fix/ci-auto-lock-${TS}"
    git switch -c "${BRANCH}"
    git add package-lock.json
    git config user.name "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    git commit -m "fix(ci): auto-sync package-lock for failed run ${RUN_ID}"
    git push --set-upstream origin "${BRANCH}"

    PR_URL="$(gh pr create --base main --head "${BRANCH}" \
      --title "fix(ci): auto-sync package-lock (run ${RUN_ID})" \
      --body "Auto-generated by ci-watchdog.\n\n- source run: ${RUN_URL}\n- action: reran npm install and committed package-lock drift fix.\n\nFailed jobs summary:\n${FAILED_JOB_SUMMARY}" )"

    gh pr merge --auto --squash "${PR_URL}" || true
    echo "Auto-fix PR created: ${PR_URL}"
    exit 0
  fi
fi

ISSUE_TITLE="ci-watchdog: manual triage required for failed run ${RUN_ID}"
EXISTING="$(gh issue list --state open --search "${ISSUE_TITLE} in:title" --json number -L 1 | node -e "const fs=require('fs');const d=JSON.parse(fs.readFileSync(0,'utf8'));if(d[0])process.stdout.write(String(d[0].number));")"

if [[ -z "${EXISTING}" ]]; then
  ISSUE_BODY="CI run failed and no deterministic auto-fix was found.\n\n- run: ${RUN_URL}\n- branch: ${HEAD_BRANCH}\n- sha: ${HEAD_SHA}\n\nFailed jobs summary:\n${FAILED_JOB_SUMMARY}\n\nPlease triage logs and patch manually."
  HAS_CI_LABEL="$(
    gh label list --limit 200 --json name \
      | node -e "const fs=require('fs');const labels=JSON.parse(fs.readFileSync(0,'utf8'));process.stdout.write(labels.some(l=>l.name==='ci')?'true':'false');"
  )"
  if [[ "${HAS_CI_LABEL}" == "true" ]]; then
    gh issue create --title "${ISSUE_TITLE}" --body "${ISSUE_BODY}" --label "ci"
  else
    gh issue create --title "${ISSUE_TITLE}" --body "${ISSUE_BODY}"
  fi
  echo "Created triage issue for run ${RUN_ID}."
else
  echo "Triage issue already exists: #${EXISTING}"
  gh issue comment "${EXISTING}" --body "New failing CI run observed.\n\n- run: ${RUN_URL}\n- branch: ${HEAD_BRANCH}\n- sha: ${HEAD_SHA}\n\nFailed jobs summary:\n${FAILED_JOB_SUMMARY}" || true
fi

exit 0
